[Migration]
Hash = "5971432415107706218"
Initial = false
Dependency = 16
Replaces = []

[[Migration.Operations]]
Type = "RenameModel"
Old = "findingdefinitionfindingcategoryrelation"
New = "findingdefinitioncategoryrelation"

[[Migration.Operations]]
Type = "RenameField"
TableName = "findingdefinitioncategoryrelation"
Old = "finding_definition"
New = "definition"

[[Migration.Operations]]
Type = "RenameField"
TableName = "findingdefinitioncategoryrelation"
Old = "finding_category"
New = "category"

[[Migration.Operations]]
Type = "RenameField"
TableName = "findingfindingcategoryrelation"
Old = "finding_category"
New = "category"
